# Generated by Django 2.1.3 on 2018-11-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_unit', models.CharField(max_length=100)),
                ('bathrooms', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('home_size', models.IntegerField()),
                ('home_type', models.CharField(max_length=100)),
                ('last_sold_date', models.DateField()),
                ('last_sold_price', models.IntegerField()),
                ('link', models.TextField()),
                ('price', models.IntegerField()),
                ('property_size', models.IntegerField()),
                ('rent_price', models.IntegerField()),
                ('rentzestimate_amount', models.IntegerField()),
                ('rentzestimate_last_updated', models.DateField()),
                ('tax_value', models.IntegerField()),
                ('tax_year', models.IntegerField()),
                ('year_built', models.IntegerField()),
                ('zestimate_amount', models.IntegerField()),
                ('zestimate_last_updated', models.DateField()),
                ('zillow_id', models.IntegerField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
            ],
        ),
    ]
